describe('Wheel.Utils.pluralize(word)', function() {
  var WORDS = [
    ["search"      , "searches"],
    ["switch"      , "switches"],
    ["fix"         , "fixes"],
    ["box"         , "boxes"],
    ["process"     , "processes"],
    ["address"     , "addresses"],
    ["case"        , "cases"],
    ["stack"       , "stacks"],
    ["wish"        , "wishes"],
    ["category"    , "categories"],
    ["query"       , "queries"],
    ["ability"     , "abilities"],
    ["agency"      , "agencies"],
    ["movie"       , "movies"],
    ["archive"     , "archives"],
    ["index"       , "indices"],
    ["wife"        , "wives"],
    ["safe"        , "saves"],
    ["half"        , "halves"],
    ["move"        , "moves"],
    ["salesperson" , "salespeople"],
    ["person"      , "people"],
    ["spokesman"   , "spokesmen"],
    ["man"         , "men"],
    ["woman"       , "women"],
    ["basis"       , "bases"],
    ["diagnosis"   , "diagnoses"],
    ["diagnosis_a" , "diagnosis_as"],
    ["datum"       , "data"],
    ["medium"      , "media"],
    ["analysis"    , "analyses"],
    ["node_child"  , "node_children"],
    ["child"       , "children"],
    ["experience"  , "experiences"],
    ["day"         , "days"],
    ["comment"     , "comments"],
    ["foobar"      , "foobars"],
    ["newsletter"  , "newsletters"],
    ["quiz"        , "quizzes"],
    ["perspective" , "perspectives"],
    ["ox"          , "oxen"],
    ["photo"       , "photos"],
    ["buffalo"     , "buffaloes"],
    ["tomato"      , "tomatoes"],
    ["dwarf"       , "dwarves"],
    ["elf"         , "elves"],
    ["bus"         , "buses"],
    ["status"      , "statuses"],
    ["status_code" , "status_codes"],
    ["mouse"       , "mice"],
    ["louse"       , "lice"],
    ["house"       , "houses"],
    ["octopus"     , "octopi"],
    ["virus"       , "viri"],
    ["alias"       , "aliases"],
    ["portfolio"   , "portfolios"],
    ["vertex"      , "vertices"],
    ["matrix"      , "matrices"],
    ["matrix_fu"   , "matrix_fus"],
    ["shoe"        , "shoes"],
    ["horse"       , "horses"],
    ["prize"       , "prizes"],
    ["edge"        , "edges"],
    ["axis"        , "axes"],
    ["testis"      , "testes"],
    ["crisis"      , "crises"]
  ];

  $.each(WORDS, function(i, words) {
    (function(baseWord, pluralizedWord) {
      it('converts ' + baseWord + ' to ' + pluralizedWord, function() {
        expect(Wheel.Utils.pluralize(baseWord)).toBe(pluralizedWord);
      });
    })(words[0], words[1]);
  });
});
